/*
 *
 */
module.exports = {
  initialize: jest.fn(),
  shutdown: jest.fn(),
  findUser: jest.fn(),
  isRegisteredUser: jest.fn(),
  addOrModifyUser: jest.fn(),
  modifyUser: jest.fn(),
  deleteInvite: jest.fn(),
  deleteUser: jest.fn(),
  ignore: jest.fn(),
  getUser: jest.fn(),
  getUsers: jest.fn(),
  isValidInviteId: jest.fn(),
  isValidIndexAndLimit: jest.fn(),
  isValidUserId: jest.fn(),
  isValidPostcardId: jest.fn(),
  isValidIndex: jest.fn(),
  isValidLimit: jest.fn(),
  getConnections: jest.fn(),
  getBlocked: jest.fn(),
  addBlocked: jest.fn(),
  deleteBlocked: jest.fn(),
  deleteConnection: jest.fn(),
  isIgnored: jest.fn(),
  addInvite: jest.fn(),
  isBlocked: jest.fn(),
  addPostcard: jest.fn(),
  getPostcards: jest.fn(),
  getInbox: jest.fn(),
  removeFromInbox: jest.fn(),
  setAsRead: jest.fn(),
  connectWithSender: jest.fn(),
  getSent: jest.fn(),
  removeFromSent: jest.fn(),
};
