apiVersion: v1
kind: Service
metadata:
  name: postcard-api
spec:
  selector:
    app: postcard-api
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postcard-api
  labels:
    app: postcard-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postcard-api
  template:
    metadata:
      labels:
        app: postcard-api
    spec:
      containers:
        - name: postcard-api
          image: postcard-api
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postcard-environment
          volumeMounts:
            - name: postcard-secret
              mountPath: '/run/secrets/POSTCARD_POSTGRES_PASSWORD'
              readOnly: true
              subPath: POSTCARD_POSTGRES_PASSWORD
            - name: postcard-secret
              mountPath: '/run/secrets/POSTCARD_S3_ACCESS_KEY'
              readOnly: true
              subPath: POSTCARD_S3_ACCESS_KEY
            - name: postcard-secret
              mountPath: '/run/secrets/POSTCARD_S3_SECRET_ACCESS_KEY'
              readOnly: true
              subPath: POSTCARD_S3_SECRET_ACCESS_KEY
            - name: postcard-secret
              mountPath: '/run/secrets/POSTCARD_SES_ACCESS_KEY'
              readOnly: true
              subPath: POSTCARD_SES_ACCESS_KEY
            - name: postcard-secret
              mountPath: '/run/secrets/POSTCARD_SES_SECRET_ACCESS_KEY'
              readOnly: true
              subPath: POSTCARD_SES_SECRET_ACCESS_KEY
      volumes:
        - name: postcard-secret
          secret:
            secretName: postcard-secret
            items:
              - key: POSTCARD_POSTGRES_PASSWORD
                path: POSTCARD_POSTGRES_PASSWORD
              - key: POSTCARD_S3_ACCESS_KEY
                path: POSTCARD_S3_ACCESS_KEY
              - key: POSTCARD_S3_SECRET_ACCESS_KEY
                path: POSTCARD_S3_SECRET_ACCESS_KEY
              - key: POSTCARD_SES_ACCESS_KEY
                path: POSTCARD_SES_ACCESS_KEY
              - key: POSTCARD_SES_SECRET_ACCESS_KEY
                path: POSTCARD_SES_SECRET_ACCESS_KEY
