apiVersion: v1
kind: Service
metadata:
  name: postcard-wss
spec:
  selector:
    app: postcard-wss
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postcard-wss
  labels:
    app: postcard-wss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postcard-wss
  template:
    metadata:
      labels:
        app: postcard-wss
    spec:
      containers:
        - name: postcard-wss
          image: postcard-wss
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postcard-environment
